# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CMake@1
  name: Configure
  inputs:
    cmakeArgs: ".."
    runInsideShell: true
    workingDirectory: build

- task: CMake@1
  name: Build
  inputs:
    cmakeArgs: "--build . --config Debug"
    runInsideShell: true
    workingDirectory: build

- script: ctest . --output-on-failure --no-compress-output
  name: CTest 
  workingDirectory: build
  failOnStderr: true
